-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id serial,
    username "char",
    punktstand integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.spiele
(
    id serial,
    spieltag integer NOT NULL,
    heimteam "char" NOT NULL,
    "auswärtsteam" "char" NOT NULL,
    heimtore integer NOT NULL DEFAULT 0,
    "auswärsttore" integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipps
(
    userid serial,
    spielid serial,
    tippheimtore integer,
    "tippauswärtstore" integer,
    punkte integer,
    PRIMARY KEY (userid, spielid)
);

ALTER TABLE IF EXISTS public.tipps
    ADD CONSTRAINT "user id" FOREIGN KEY (userid)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tipps
    ADD CONSTRAINT "spiel id" FOREIGN KEY (spielid)
    REFERENCES public.spiele (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;